{{- if .Values.validators.privKey -}}
{{- $fullname := (include "pantheon-node.fullname" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pantheon-node.fullname" . }}-validators
  labels:
    app.kubernetes.io/name: {{ include "pantheon-node.name" . }}-validators
    helm.sh/chart: {{ include "pantheon-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  private.key: |-
    {{ .Values.validators.privKey | b64enc }}

{{- end -}}