---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pantheon-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pantheon-node.name" . }}
    helm.sh/chart: {{ include "pantheon-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.node.rpc.port }}
      targetPort: http
    - name: ws
      port: {{ .Values.node.ws.port }}
      targetPort: ws
    - name: graphql
      port: {{ .Values.node.graphql.port }}
      targetPort: graphql
    - name: p2p-tcp
      port: {{ .Values.node.p2p.port }}
      targetPort: p2p-tcp
      protocol: TCP
    - name: p2p-udp
      port: {{ .Values.node.p2p.port }}
      targetPort: p2p-udp
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "pantheon-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
