helmDefaults:
  verify: false
  wait: true # wait that pod is up and ready before ending helm action
  timeout: 600
  recreatePods: false
  force: false
  atomic: true

releases:
  ##################################
  # Bootnode
  ##################################
  - name: bootnode
    labels:
      component: bootnode
    namespace: {{ .Namespace }}
    chart: ../pantheon-node
    values:
      - ../values/bootnode.yaml
